name: pylint

on:
  pull_request:
    types: [opened, reopened]

  # Temporarily allow running this workflow from actions tab.\
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        OUTPUT=$(pylint $(git ls-files '*.py'))
        RATING=$(printf "$OUTPUT" | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p')
        echo "PYLINTSCORE=$RATING" >> $GITHUB_ENV
    - name: Check Scan result
      if: ${{ env.PYLINTSCORE }} <= ${{ 7.0 }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Did not pass scans.')
