name: Run Runner

on:
  schedule:
    - cron: '00 00 * * 0'    

  # Temporarily allow running this workflow from actions tab.\
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python -m pip install -r requirements.txt
    - name: Run the python script
      run: |
        python -m mangaweb.runners.runner
